[pytest]
norecursedirs = workspace .git .pytest_cache
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::FutureWarning
    ignore::UserWarning
    ignore::Warning
    ignore::ResourceWarning
